name: Build
on:
  push:
    branches:
      - '*'
env:
  GO_VERSION: 1.19
  CGO_ENABLED: 0
  DOCKERHUB_REPO: "hellowoodes/flare"

jobs:

  build-webui:
    runs-on: ubuntu-20.04

    steps:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: Set up Go
            uses: actions/setup-go@v3
            with:
              go-version: 1.19

          - name: Build
            run: go run build/build.go && go build -o bin/flare main.go

          - name: Copy Assets
            run: go run build/build.go

          - name: Build Binary
            run: go build -o bin/flare main.go

          - name: Build Image
            run: sh ./build/docker-image-build.sh

          - name: Push Image
            run: sh ./build/docker-image-push-latest.sh